$(document).ready(function(){
	$("#chartDiv").load("Home.html");
	$("#salesByType").click(function(){
		$("#chartDiv").empty();
		$("#chartDiv").load("Sales-By-Type.html");	
	});
	$("#home").click(function(){
		$("#chartDiv").load("Home.html");
	});
});
