var jsondata = {
    "policies": [
        {
        	"agent":"ABC Corp",
            "type": "Medical",
            "sex": "female",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
        	"agent":"ABC Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
            "agent":"ABC Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"ABC Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"ABC Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"ABC Corp",
            "type": "Medical",
            "sex": "female",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"ABC Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Medical",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
            "agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
            "agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
            "agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
            "agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "approved"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"XYZ Corp",
            "type": "Vehicle",
            "sex": "female",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "sold"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"Lifesaver Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"Lifesaver Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "28",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"Lifesaver Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Calicut",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Vehicle",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
         {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "18",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Trivandrum",
            "date": "29-March-2015",
            "status": "surrendered"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "21",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        },
        {
        	"agent":"ABC Corp",
            "type": "Life",
            "sex": "male",
            "country": "India",
            "age": "35",
            "State": "Kerala",
            "city": "Kochi",
            "date": "29-March-2015",
            "status": "lapsed"
        }
        
        
    ]
}
